# Generated by Django 4.2.1 on 2023-05-14 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 8, 12, 47, 777900)),
        ),
    ]
