# Generated by Django 4.2.1 on 2023-05-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_thing_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='created',
            field=models.DateTimeField(default='django.utils.timezone.now'),
        ),
    ]
