# Generated by Django 4.2.1 on 2023-05-14 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_thing_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 8, 16, 16, 385275, tzinfo=datetime.timezone.utc)),
        ),
    ]
