# Generated by Django 4.2.1 on 2023-05-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0002_delete_thing_remove_book_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
