# Generated by Django 4.2.1 on 2023-05-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0004_book_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stats',
            field=models.JSONField(default=dict),
        ),
    ]
